### PR TITLE
Update.readme

### PR DESCRIPTION
**Pull request by ilaflott**

### CODE REVIEW

**Review by ceblanton — APPROVED** [review]
Thanks Ian for starting this needed documentation. It's tough as we haven't done it so far in part because this "workflow definition" repository is not usable without fre-cli. Should "how to postprocess fms history files" be in this repository or in fre-cli?

this is in the right direction, thanks!

**Review by ceblanton — COMMENTED** [review]
I like where this is going but it needs some work.

We're not using the Rose optional configurations any longer so some of the steps can be simplified.

Should we document how to create the rose-suite.conf and rose-app.conf's manually, or only document how to use `fre pp configure-yaml`?

**Comment by ilaflott** [comment]
_**> We're not using the Rose optional configurations any longer so some of the steps can be simplified.**_
shall remove!

_**> Should we document how to create the rose-suite.conf and rose-app.conf's manually, or only document how to use `fre pp configure-yaml`?**_
was thinking that we should link [`fre pp`'s README](https://github.com/NOAA-GFDL/fre-cli/tree/main/fre/pp), somewhere- the logic being that if someone is looking at this repo and wondering... "shouldn't this be a little bit easier?", they're probably actually looking for `fre-cli` and somehow ended up here, in `fre-workflows`

**Comment by ilaflott** [comment]
Good enough for now. Illustrates what the user needs to pay attention to, and the instructions are copy/paste oriented enough.

A problem for an issue+PR: statics processing task-dependence is not right (screen shot)
Screen Shot 2024-08-07 at 12 59 11 PM. #8

**Pull request merged**
